### ISSUE TITLE
browse lemmas gives error

### ISSUE THREAD

**Issue by fxru** [cceh/sanskrit-web#42]
The following error is raised when following a link to `/dictionary/monier/monier/lemmas`:

   No route matches [GET] "/dictionary/monier/monier/lemmas"

**Comment by gioele** [comment]
I have not been able to reproduce this. I suspect there are some cases in which the interface may produce broken links, but I could not find one at the moment. We should reopen this bug (or a new one) should we find a situation where this problem shows up repeatedly.
