### ISSUE TITLE
Virama seem to be missing

### ISSUE THREAD

**Issue by fxru** [cceh/sanskrit-web#60]
The line `wie <w xml:lang="san-Latn-x-SLP1">Urja</w> aus <w xml:lang="san-Latn-x-SLP1">Urj</w>` in `lemma-iza` 

> ऊर्ज aus ऊर्ज््

but is rendered as

![urj](https://cloud.githubusercontent.com/assets/1352294/5473558/8f2cf33e-860a-11e4-84aa-9363f8bb55d7.png)

The second form ऊर्ज्् `SLP1: Urj` seems to lack the virama.

**Comment by gioele** [comment]
The transliteration library adds the virama where needed. I wonder what did cause this problem.
