### ISSUE TITLE
ISO15919 error for SLP1:e 

### ISSUE THREAD

**Issue by fxru** [cceh/sanskrit-web#65]
SLP1 `e` is converted into `ē` (`e` with macron), but it should be plain `e`. This is consistently wrong in the display. (Not sure how the ISO->SLP1 parsing treats `ē` or `e`. See issue #64.)

**Comment by gioele** [comment]
Should we use `o` for `ō` as well?

**Comment by gioele** [comment]
The code generates `e` instead of `ē` now.
