### ISSUE TITLE
MouseOver fields are overlapping

### ISSUE THREAD

**Issue by textloop** [cceh/sanskrit-web#74]
Sometimes the user is facing problems to see both mouseOver fields: 

![monier_ams_mouseover](https://cloud.githubusercontent.com/assets/7046115/12551825/92e27548-c36d-11e5-9dc9-6d08b2b86b40.jpg)

**Comment by textloop** [comment]
e.g. search for aMs in monier

**Comment by gioele** [comment]
The problem is caused by a `<span class="tei-w"/>` element caused by an unhandled root encoded as `<w ana="root" type="root" />` in the TEI file.

I have added this case to the main bug for root, issue #70.
