### ISSUE TITLE
Landing page, entry "project team"

### ISSUE THREAD

**Issue by PatrickSahle** [cceh/sanskrit-web#77]
please upload a simple page on the project team so that the link on the landing page is working

As far as I know, Martina has provided a draft fo such a page

**Comment by PatrickSahle** [comment]
@gioele ? Could you please react on this? It's a very uncomfortable situation to spend more time on thinking and reminding for me than it would take time to do something for you ...
Or do we have a more fundamental problem here? In that case: please react as well an explain. Thanks.

**Comment by gioele** [comment]
Fixed 2017-01-13 in commit 2ccce6d05c5e95eba597f0771fda2b2a0e8b485e (private cceh branch). This issue has not been autoclosed because GitHub never saw that private commit.
