### ISSUE TITLE
Landing page, other resources, documentation

### ISSUE THREAD

**Issue by PatrickSahle** [cceh/sanskrit-web#78]
please either ...

- upload a documentation page
- or take off the entry and link "Documentation"

**Comment by PatrickSahle** [comment]
@gioele? Could you please react on this? It's a very uncomfortable situation to spend more time on thinking and reminding for me than it would take time to do something for you ...
Or do we have a more fundamental problem here? In that case: please react as well an explain. Thanks.

**Comment by gioele** [comment]
Fixed 2017-01-12 in commit 857149f7cac0dcc18d6a311498f2024ef56f6d8a (private cceh branch). This issue has not been autoclosed because GitHub never saw that private commit.
