### ISSUE TITLE
Landing page, other resources, downloads

### ISSUE THREAD

**Issue by PatrickSahle** [cceh/sanskrit-web#79]
please either ...

- provide a page for the downloads
- take off the entry and link Downloads (dictionaries, TEI ODD schemas)

**Comment by PatrickSahle** [comment]
@gioele? Could you please react on this? It's a very uncomfortable situation to spend more time on thinking and reminding for me than it would take time to do something for you ...
Or do we have a more fundamental problem here? In that case: please react as well an explain. Thanks.

**Comment by gioele** [comment]
Fixed a long time ago in commit 3741d62cc315d4ae37c2c5c52a61bac03e3a9f4f (private cceh branch). This issue has not been autoclosed because GitHub never saw that private commit.
